/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bob_jnidemo_ScrollingActivity */

#ifndef _Included_com_bob_jnidemo_ScrollingActivity
#define _Included_com_bob_jnidemo_ScrollingActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bob_jnidemo_ScrollingActivity
 * Method:    scanDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_bob_jnidemo_MainActivity_scanDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bob_jnidemo_ScrollingActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bob_jnidemo_MainActivity_getStringFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_bob_jnidemo_ScrollingActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bob_jnidemo_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_bob_jnidemo_ScrollingActivity
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bob_jnidemo_MainActivity_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
